version: '3.8'

services:
  dice:
    container_name: dice
    build:
      context: .
      dockerfile: ./dice/Dockerfile
    volumes:
      - ./certs:/certs
    networks:
      - dice-net

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/certs
    ports:
      - "50052:443" # Можно дергать снаружи, но Gateway ходит внутри сети на 443
    depends_on:
      - dice
    networks:
      - dice-net

  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    volumes:
      - ./certs:/certs
    depends_on:
      - nginx
    networks:
      - dice-net

networks:
  dice-net: