events {}

http {
    server {
        listen 80;

        location / {
            # Проксируем HTTP-запрос к Gateway
            proxy_pass http://gateway:8080;

            # Стандартные заголовки для проксирования
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 443 ssl http2;
        server_name nginx;

        # Сертификаты для Nginx (чтобы Dice доверял Nginx)
        ssl_certificate     /certs/server.crt;
        ssl_certificate_key /certs/server.key;

        location / {
            # Проксируем на Dice. grpcs означает gRPC поверх TLS/SSL
            grpc_pass grpcs://dice:50051;

            # Разрешаем Nginx доверять самоподписанному сертификату Generator'а
            grpc_ssl_verify off;
            grpc_ssl_server_name on;
        }
    }
}